spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.mayikt.entity

#showSql
logging:
  level:
    com:
      mayikt:
        mapper: debug

pagehelper:
  helper-dialect: mysql